"""initial_schema

Revision ID: 16a8cdde3845
Revises: 
Create Date: 2026-03-14 14:20:38.621205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a8cdde3845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_path', 'audit_log', ['path'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.Column('alias_value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aliases_alias_value', 'aliases', ['alias_value'], unique=False)
    op.create_index('idx_aliases_part_id', 'aliases', ['part_id'], unique=False)
    # FTS5 virtual tables must be dropped via raw SQL (SQLite vtable constructor issue)
    # Dropping the main table first causes SQLite to auto-remove shadow tables
    op.execute("DROP TABLE IF EXISTS parts_fts")
    op.execute("DROP TABLE IF EXISTS parts_fts_data")
    op.execute("DROP TABLE IF EXISTS parts_fts_idx")
    op.execute("DROP TABLE IF EXISTS parts_fts_config")
    op.execute("DROP TABLE IF EXISTS parts_fts_docsize")
    op.alter_column('guide_parts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('guide_parts', 'guide_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('guide_parts', 'part_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('guide_parts', 'confidence_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('guide_parts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_guide_part', 'guide_parts', ['guide_id', 'part_number'])
    op.alter_column('part_guides', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('part_guides', 'part_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('part_guides', 'guide_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('part_guides', 'confidence_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('part_guides', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_part_guide', 'part_guides', ['part_id', 'guide_id'])
    op.alter_column('part_images', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('part_images', 'part_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('part_images', 'image_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('part_images', 'image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('part_images', 'image_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('part_images', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('part_images', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_part_image', 'part_images', ['part_id', 'image_filename'])
    op.add_column('parts', sa.Column('confidence_label', sa.String(length=30), nullable=False))
    op.add_column('parts', sa.Column('review_status', sa.String(length=20), nullable=False))
    op.add_column('parts', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('parts', sa.Column('reviewed_by', sa.String(length=100), nullable=True))
    op.add_column('parts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('parts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('parts', 'catalog_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('parts', 'catalog_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parts', 'part_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parts', 'part_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('parts', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parts', 'image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('parts', 'pdf_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('parts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_oe_numbers', table_name='parts')
    op.drop_index('idx_page', table_name='parts')
    op.create_index('idx_published', 'parts', ['published'], unique=False)
    op.create_index('idx_review_status', 'parts', ['review_status'], unique=False)
    op.create_unique_constraint('uq_part_catalog_page', 'parts', ['catalog_name', 'part_number', 'page'])
    op.add_column('technical_guides', sa.Column('confidence_label', sa.String(length=30), nullable=False))
    op.add_column('technical_guides', sa.Column('review_status', sa.String(length=20), nullable=False))
    op.alter_column('technical_guides', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('technical_guides', 'guide_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('technical_guides', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('technical_guides', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('technical_guides', 's3_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('technical_guides', 'pdf_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('technical_guides', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technical_guides', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('technical_guides', 'pdf_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('technical_guides', 's3_key',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('technical_guides', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('technical_guides', 'display_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('technical_guides', 'guide_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('technical_guides', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('technical_guides', 'review_status')
    op.drop_column('technical_guides', 'confidence_label')
    op.drop_constraint('uq_part_catalog_page', 'parts', type_='unique')
    op.drop_index('idx_review_status', table_name='parts')
    op.drop_index('idx_published', table_name='parts')
    op.create_index('idx_page', 'parts', ['page'], unique=False)
    op.create_index('idx_oe_numbers', 'parts', ['oe_numbers'], unique=False)
    op.alter_column('parts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('parts', 'pdf_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('parts', 'image_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('parts', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('parts', 'part_number',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('parts', 'part_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('parts', 'catalog_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('parts', 'catalog_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('parts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('parts', 'reviewed_at')
    op.drop_column('parts', 'reviewed_by')
    op.drop_column('parts', 'published')
    op.drop_column('parts', 'review_status')
    op.drop_column('parts', 'confidence_label')
    op.drop_constraint('uq_part_image', 'part_images', type_='unique')
    op.alter_column('part_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('part_images', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('part_images', 'image_type',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('part_images', 'image_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('part_images', 'image_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('part_images', 'part_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part_images', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_part_guide', 'part_guides', type_='unique')
    op.alter_column('part_guides', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('part_guides', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('part_guides', 'guide_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part_guides', 'part_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part_guides', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_guide_part', 'guide_parts', type_='unique')
    op.alter_column('guide_parts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('guide_parts', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('guide_parts', 'part_number',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('guide_parts', 'guide_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('guide_parts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # Recreate FTS5 virtual table via raw SQL on downgrade
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS parts_fts USING fts5(
            catalog_name, catalog_type, part_number, description,
            page_text, machine_info, specifications, oe_numbers, applications,
            content='parts', content_rowid='id'
        )
    """)
    op.drop_index('idx_aliases_part_id', table_name='aliases')
    op.drop_index('idx_aliases_alias_value', table_name='aliases')
    op.drop_table('aliases')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_path', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
